### ISSUE TITLE
官方docker镜像成功启动后，worker一直没有加载

### ISSUE THREAD

**Issue by lichtud** [PowerJob/PowerJob#1020]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details. 

官方docker镜像成功启动后，worker一直没有加载，日志没有报错
![image](https://github.com/user-attachments/assets/1e79ed82-139e-40ed-94fb-321d50eb75ff)

![image](https://github.com/user-attachments/assets/d137c6e0-8c52-49a2-9b6b-1749b129fa10)

**Comment by kingchang** [comment]
Do you create app on the powerjob-server ?

**Comment by lichtud** [comment]
> Do you create app on the powerjob-server ?

I create a docker-compose job including powerjob-worker-samples,powerjob-server and powerjob-mysql,but i can`t find a 
 worker like offical guide after  create a appname.

**Comment by kingchang** [comment]
You need to change the app name from 'powerjob-work-samples' to 'test'.
like below
```yaml
powerjob-worker-samples:
    container_name: powerjob-worker-samples
    image: powerjob/powerjob-worker-samples:latest
    restart: always
    depends_on:
      - powerjob-mysql
      - powerjob-server
    ports:
      - "8081:8081"
      - "27777:27777"
    volumes:
      - ./powerjob-data/powerjob-worker-samples:/root/powerjob/worker
      - ./others/script/wait-for-it.sh:/wait-for-it.sh
    entrypoint:
      - "sh"
      - "-c"
      - "chmod +x wait-for-it.sh && ./wait-for-it.sh powerjob-server:7700 --strict -- java -Xmx512m -jar /powerjob-worker-samples.jar --powerjob.worker.server-address=powerjob-server:7700 --powerjob.worker.app-name=test"
```
