### ISSUE TITLE
开发服务无法注册上k8s的server，请问我应该如何注册？

### ISSUE THREAD

**Issue by shouziws** [PowerJob/PowerJob#1097]
我本地服务注册部署在k8s中的powerjob无法注册成功
报错如下：
2025-04-27 11:34:43.745  WARN 59239 --- [ntloop-thread-3] t.p.remote.http.vertx.VertxTransporter   : [VertxTransporter] post to url[URL(serverType=SERVER, address=10.88.49.220:10010, location=HandlerLocation(rootPath=server, methodPath=workerHeartbeat))] failed,msg: ConnectTimeoutException: connection timed out aft
er 3000 ms: /10.88.49.220:10010

我的配置如下：

<img width="672" alt="Image" src="https://github.com/user-attachments/assets/b9bc5edb-d5f7-49ca-922b-8aeadd41eaa0" />

如何我将客户端服务部署到k8s中，就能正常注册并且使用。 

请问 http、akka、server地址能不能单独配置？
这是我的k8s配置
<img width="611" alt="Image" src="https://github.com/user-attachments/assets/093851ac-5e1f-40af-ba11-5981fabae0cb" />

<img width="404" alt="Image" src="https://github.com/user-attachments/assets/90c89f0a-5624-4e57-b390-bfa41ee3af74" />

**Comment by liangweidonggood** [comment]
```
- name: PARAMS
  value: --spring.profiles.active=product --server.port=7700 --oms.akka.port=30604 --oms.http.port=30605
```
server端启动时加上参数
service配置
```
spec:
  type: NodePort
  ports:
    - name: port7700
      port: 7700
      targetPort: 7700
      nodePort: 30603
    - name: port30604
      port: 30604
      targetPort: 30604
      nodePort: 30604
    - name: port30605
      port: 30605
      targetPort: 30605
      nodePort: 30605
```
