### ISSUE TITLE
server异常退出

### ISSUE THREAD

**Issue by LockiJiang** [PowerJob/PowerJob#291]
### server端
基于server 4.0.2（SHA：ee2bb727185fd38cb244efe0e537b5b3c599d331）
增加神通数据库支持
```
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OscarDialect
spring.datasource.core.driver-class-name=com.oscar.Driver
```
### agent
4.0.1官方docker镜像

## 启动docker-compose.yml
```
version: "3"

services:

  mongo-service:
    image: mongo:4.2.14
    ports:
      - "27017:27017"

  powerjob-server:
    image: www.harbor.csbi/public/powerjob-server:v4.0.2-oscar
    ports:
      - "7700:7700"
    environment:
      - PARAMS=--spring.datasource.core.jdbc-url=jdbc:oscar://10.100.9.63:2005/JGDCNEW --spring.datasource.core.username=dataxweb --spring.datasource.core.password=dataxweb --spring.data.mongodb.uri=mongodb://mongo-service:27017/powerjob-product
    depends_on:
      - mongo-service
  
  powerjob-agent-1:
    image: tjqq/powerjob-agent:4.0.1
    expose:
      - "27777"
    environment:
      - PARAMS=--app simple --server powerjob-server:7700
    depends_on:
      - powerjob-server
```
### 1、独立启动server出现H2相关异常
![图片](https://user-images.githubusercontent.com/16129287/121819030-91af4480-ccbd-11eb-822c-cb612783c2a4.png)
### 2、数据库序列自增异常(本地测试使用同一数据库)
![图片](https://user-images.githubusercontent.com/16129287/121819093-e05cde80-ccbd-11eb-86ba-99562d8c6b1d.png)
### 3、启动agent，server直接退出，且未输出错误信息(docker logs -f xxx直接退出，docker ps -a查看已exit)

**Comment by LockiJiang** [comment]
> 
> ## 软件版本：
> ### server端
> 
> 基于server 4.0.2（SHA：ee2bb727185fd38cb244efe0e537b5b3c599d331）
> 增加神通数据库支持
> 
> ```
> spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OscarDialect
> spring.datasource.core.driver-class-name=com.oscar.Driver
> ```
> 
> ### agent
> 
> 4.0.1官方docker镜像
> ## 启动docker-compose.yml
> 
> ```
> version: "3"
> 
> services:
> 
>   mongo-service:
>     image: mongo:4.2.14
>     ports:
>       - "27017:27017"
> 
>   powerjob-server:
>     image: www.harbor.csbi/public/powerjob-server:v4.0.2-oscar
>     ports:
>       - "7700:7700"
>     environment:
>       - PARAMS=--spring.datasource.core.jdbc-url=jdbc:oscar://10.100.9.63:2005/JGDCNEW --spring.datasource.core.username=dataxweb --spring.datasource.core.password=dataxweb --spring.data.mongodb.uri=mongodb://mongo-service:27017/powerjob-product
>     depends_on:
>       - mongo-service
>   
>   powerjob-agent-1:
>     image: tjqq/powerjob-agent:4.0.1
>     expose:
>       - "27777"
>     environment:
>       - PARAMS=--app simple --server powerjob-server:7700
>     depends_on:
>       - powerjob-server
> ```
> 
> ## 现象
> ### 1、独立启动server出现H2相关异常
> 
> ![图片](https://user-images.githubusercontent.com/16129287/121819030-91af4480-ccbd-11eb-822c-cb612783c2a4.png)
> ### 2、数据库序列自增异常(本地测试使用同一数据库)
> 
> ![图片](https://user-images.githubusercontent.com/16129287/121819093-e05cde80-ccbd-11eb-86ba-99562d8c6b1d.png)
> ### 3、启动agent，server直接退出，且未输出错误信息(docker logs -f xxx直接退出，docker ps -a查看已exit)


### 目前怀疑是官方agent启动资源占用过大，启动一个agent后服务器CPU资源使用直接由44MHz升至5.18GHz
限制资源后暂时正常
```
powerjob-agent-1:
    image: tjqq/powerjob-agent:4.0.1
    expose:
      - "27777"
    environment:
      - PARAMS=--app simple --server powerjob-server:7700
    depends_on:
      - powerjob-server
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 200M
```
